WIP MAUT-7558 : Block modification of custom object unique value if custom object has data
acquia/mc-cs-plugin-custom-objects pull request #283
Opened 2022-09-11 18:48 UTC by rahuld-dev

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | No
| New feature/enhancement? (use the a.x branch)      | Yes
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | https://backlog.acquia.com/browse/MAUT-7885 

#### Description:

Block edit operation of custom object if customer tries to add new unique value for exiting custom object or modify existing unique identifier for a custom object

1) If data doesn't exists then allow modification or creation of new unique value column
2) If data exists then do not allow

Note: If they want modify exiting unique value for custom object then they can create new custom object and all import custom items

Status code for api: 422/400

#### Steps to test this PR:

1. Open this PR for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2022-09-12 06:52 UTC, shinde-rahul commented on Form/Validator/Constraints/AllowUniqueIdentifierValidator.php
> +}
```suggestion
}

```

2022-09-12 11:15 UTC, dadarya0 requested changes

2022-09-12 11:15 UTC, dadarya0 commented on Repository/CustomItemRepository.php
> +
set limit 1 if you are using this function only for checking record exist or not.

2022-09-12 13:13 UTC, diaboloshogunate approved these changes
Thank you @rahuld-dev

2022-09-13 05:32 UTC, dadarya0 approved these changes

2022-10-17 10:37 UTC, merged