[BUGIX] Add plugin-enabled check condition to CustomObjectPermissions…
acquia/mc-cs-plugin-custom-objects pull request #292
Opened 2022-12-06 21:58 UTC by Moongazer

To solve the issue #290, tag `1.0.0` (`94ff1e5`) was checked out. Because this resulted in a detached head, I had to create a branch which is `fix/issue-290`.

2022-12-07 09:10 UTC, escopecz submitted a review, later dismissed
Makes sense. Thanks! 👍

2022-12-07 09:19 UTC, escopecz commented
I noticed [your comment](https://github.com/acquia/mc-cs-plugin-custom-objects/issues/290#issuecomment-1340071303) and testing it you are right. It's checking the feature flag which is true by default. Let me see if I'll find a way.

2022-12-07 09:23 UTC, ts-navghane submitted a review, later dismissed
LGTM! Thanks @Moongazer!

2022-12-07 09:31 UTC, escopecz commented
We'll have to extend the https://github.com/acquia/mc-cs-plugin-custom-objects/blob/staging/Provider/ConfigProvider.php#L22 to have the Doctrine's `Connection` service dependency and then check that the plugin is installed properly by checking that the row exists for this plugin in the `plugins` table at least if not also check if at least some of the custom_object tables exist. Do you think you can add it to this PR?

2022-12-12 17:51 UTC, Moongazer commented
> Do you think you can add it to this PR?
Yes, hope I will find some time ASAP

2022-12-17 16:56 UTC, Moongazer commented
Change is done and works (tested by deleting the record from `plugins` table and renaming the plugin-table to `custom_object_xxx`). Here is the SQL to re-add the deleted record without executing `mautic:plugins:reload`:
```
INSERT INTO `plugins` (`name`, `description`, `is_missing`, `bundle`, `version`, `author`) VALUES
('Custom Objects', 'Adds custom objects and fields features to Mautic', 0, 'CustomObjectsBundle', '0.0.19', 'Mautic, Inc.');
```

2022-12-19 09:37 UTC, escopecz requested changes
Can you please still check for `(bool) $this->coreParametersHelper->get(self::CONFIG_PARAM_ENABLED, true);`? We heavily depend on that as not all customers want to use this plugin. So we use this feature flag to turn it on only for those who want to use it. From the performance stand point it would be great to first check if the feature flag (the configuration) is ON. If it is off then do not execute the SQL queries at all. If it is on then also check that the plugin is installed with the queries.

2022-12-19 13:36 UTC, Moongazer commented
OK done.

> So we use this feature flag to turn it on only for those who want to use it. 

Question: where exactly you turn this flag on/off? I could not find it anywhere, that's why it returned always `true` for me if the plugin was installed once.

2022-12-20 09:09 UTC, escopecz commented
It is set as true by default so it wouldn't complicate the installation process. Here is the documentation for the feature flag: https://github.com/acquia/mc-cs-plugin-custom-objects/wiki/Feature-flag

2022-12-20 09:12 UTC, escopecz submitted a review, later dismissed
Thanks! 👍

2022-12-20 09:28 UTC, ts-navghane commented on Provider/ConfigProvider.php
> +        $this->connection = $connection;
```suggestion
        $this->coreParametersHelper = $coreParametersHelper;
        $this->connection                    = $connection;
```

2022-12-20 09:30 UTC, ts-navghane approved these changes
LGTM! Thank you @Moongazer

2022-12-23 10:57 UTC, escopecz approved these changes

2024-06-26 15:35 UTC, PierreAmmeloot approved these changes

2025-03-17 09:07 UTC, PierreAmmeloot commented
@escopecz what's the next step?

2025-03-17 10:36 UTC, escopecz commented
> @escopecz what's the next step?

@gunnrryy?

2025-03-18 10:51 UTC, gunnrryy commented
We can merge this @escopecz

2025-03-18 11:19 UTC, merged

2025-03-18 12:06 UTC, escopecz commented
I had to revert this due to many failures in the CI. Please fix those first and then let's merge this. Rebase to the latest staging branch in order to see the checks. https://github.com/acquia/mc-cs-plugin-custom-objects/pull/366