add new route to delete items
acquia/mc-cs-plugin-custom-objects pull request #301
Opened 2023-02-16 08:35 UTC by npracht

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | ✅ 
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
It was not possible to delete items by API. We introduce a new endpoint.

#### Steps to test this PR:

1. Open this PR for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. use the API route delete Custom Items, GET /api/custom/item/delete/{itemId}

HTTP basic request example (using phpstorm):
```
POST http://localhost:8084/index_dev.php/oauth/v2/token
Accept: application/json,
Content-Type: application/json

{
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "grant_type": "client_credentials"
}

> {%
    client.global.set("auth_token", response.body.access_token);
%}

### Edit
PUT http://localhost:8084/index_dev.php/api/contacts/34690/edit
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "customObjects": {
        "data": [
            {
                "id": 2,
                "alias": "programmes",
                "data": [
                    {
                        "id": 18,
                        "name": "Hello From API2",
                        "attributes": {
                            "email": "api2@is.here"
                        }
                    }
                ]
            }
        ]
    }
}

### Edit
GET http://localhost:8084/index_dev.php/api/custom/item/delete/19
Content-Type: application/json
Authorization: Bearer {{auth_token}}
```

@escopecz i think we need to add some of this info in the wiki as well, but it seems we cannot commit wiki code.

2023-10-10 22:10 UTC, Moongazer approved these changes

2023-10-10 22:11 UTC, Moongazer commented
Would be super great if we'd be able to delete items via API, please merge and release.

2024-06-26 15:34 UTC, PierreAmmeloot approved these changes

2024-06-27 08:35 UTC, escopecz requested changes
Please add functional tests to get this merged.

2025-02-21 03:19 UTC, closed without merging