Revert "added cortex file" as this is a public repository
acquia/mc-cs-plugin-custom-objects pull request #309
Opened 2023-03-23 09:49 UTC by aarohiprasad

This PR reverts changes from https://github.com/acquia/mc-cs-plugin-custom-objects/pull/305

2023-03-23 14:40 UTC, avikarshasaha requested changes
Please resolve the conflict first.

2023-03-24 14:49 UTC, avikarshasaha approved these changes

2023-03-27 05:09 UTC, rohitp19 approved these changes

2023-03-28 08:00 UTC, aarohiprasad commented
@rohitp19 could you please merge this PR

2023-03-30 08:59 UTC, merged