[WIP] : MAUT-8990 : Upgrade to PHP8
acquia/mc-cs-plugin-custom-objects pull request #319
Opened 2023-05-25 11:15 UTC by ts-navghane

To be added...

2023-06-22 06:47 UTC, rohitp19 approved these changes, later dismissed
Approving as team already reviewed it.

2023-06-22 06:58 UTC, dadarya0 submitted a review, later dismissed

2023-12-28 11:15 UTC, dadarya0 commented on EventListener/TokenSubscriber.php
> +use MauticPlugin\CustomObjectsBundle\Entity\CustomFieldValueInt;
```suggestion
```

2023-12-28 11:16 UTC, dadarya0 requested changes
found 1 minor change.

2023-12-28 11:16 UTC, dadarya0 approved these changes

2023-12-28 11:16 UTC, dadarya0 approved these changes

2023-12-29 05:21 UTC, rohitp19 approved these changes
LGTM.

2024-01-03 09:51 UTC, dadarya0 approved these changes

2024-01-04 04:52 UTC, rohitp19 approved these changes

2024-01-09 15:35 UTC, merged