MAUT-11442: Before and After Filer in Segments | Fetch from TypeOperatorProvider
acquia/mc-cs-plugin-custom-objects pull request #344
Opened 2024-05-13 15:13 UTC by avikarshasaha

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-05-15 06:21 UTC, rahuld-dev approved these changes, later dismissed
Thanks @avikarshasaha

2024-05-24 08:45 UTC, dadarya0 approved these changes, later dismissed
Thanks @avikarshasaha working fine , tested some fields.

2024-06-14 09:52 UTC, rahuld-dev approved these changes
re-approving after fix conflicts

2024-06-14 09:55 UTC, rahuld-dev requested changes

2024-06-14 09:55 UTC, rahuld-dev commented on Tests/Unit/EventListener/SegmentFiltersChoicesGenerateSubscriberTest.php
> +                    $this->callback(function (OverrideOperatorLabelEvent $event) { // @phpstan-ignore-line
We can remove `// @phpstan-ignore-line` as file is excluded from phpstan.

2024-06-14 09:59 UTC, rahuld-dev approved these changes
Thanks @avikarshasaha

2024-06-14 10:39 UTC, rohitp19 approved these changes
Thanks @avikarshasaha 
Please remove Tests/Unit/EventListener/SegmentFiltersChoicesGenerateSubscriberTest.php from ignore list when Community PR with constants gets merged

2024-06-14 10:50 UTC, merged