Between operator for segments with numeric Custom Object fields
acquia/mc-cs-plugin-custom-objects pull request #346
Opened 2024-05-16 07:58 UTC by aarohiprasad

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-05-20 09:59 UTC, escopecz requested changes

2024-05-20 09:59 UTC, escopecz commented on Helper/QueryFilterHelper.php
> +        float|bool|array|string $filterParameterValue = null,
I'm afraid this plugin still needs to run on PHP 7.4 as defined in composer.json as someone from the community can run it on PHP 7.4 with Mautic 4. Can we remove the type here and add it as `mixed` in the comments?

Same with the return type.

2024-05-20 15:37 UTC, avikarshasaha reviewed
@aarohiprasad Please re-request for review when it is done.

2024-05-21 07:25 UTC, escopecz requested changes

2024-05-21 07:25 UTC, escopecz commented on Helper/QueryFilterHelper.php
> +    ): CompositeExpression|string {
As I noted previously, this won't work for PHP 7.4.

2024-05-21 08:46 UTC, escopecz submitted a review, later dismissed
I see no more issues, thanks!

2024-05-23 07:21 UTC, aarohiprasad commented
Only one commit has been added since the last review. Please review [8de83d7](https://github.com/acquia/mc-cs-plugin-custom-objects/pull/346/commits/8de83d72bc11c7853292fc329e5e53c322392978). @escopecz @avikarshasaha. Thank you!

2024-05-23 07:34 UTC, escopecz submitted a review, later dismissed

2024-05-23 10:43 UTC, avikarshasaha requested changes
This is not working in the beta version. @aarohiprasad is having some issues with the merging. She will fix it.

2024-05-27 10:44 UTC, avikarshasaha submitted a review, later dismissed

2024-06-06 15:10 UTC, escopecz approved these changes, later dismissed
reapproving

2024-06-07 12:13 UTC, avikarshasaha approved these changes, later dismissed

2024-06-14 08:22 UTC, avikarshasaha approved these changes

2024-06-14 08:25 UTC, rahuld-dev approved these changes
approving PR after resolved conflicts

2024-06-14 08:25 UTC, merged