WIP MAUT-11617 : Campaign -> Condition -> Custom Object Field values : Date picker unavailable for Date type fields
acquia/mc-cs-plugin-custom-objects pull request #357
Opened 2024-07-08 06:53 UTC by rahuld-dev

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

#### Steps to test this PR:

1. Open this PR for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

2024-07-09 06:21 UTC, rohitp19 submitted a review, later dismissed

2024-07-09 07:26 UTC, fedys requested changes
Thanks @rahuld-dev! Please see my code suggestion.

2024-07-09 07:26 UTC, fedys commented on Assets/js/custom-objects.js
> +        let fieldType = selectedField.attr('data-field-type');
```suggestion
        const fieldType = selectedField.attr('data-field-type');
```
Let's use `const` for variables that are never written to.

2024-07-09 07:34 UTC, fedys approved these changes, later dismissed
Thanks @rahuld-dev!

2024-07-09 07:35 UTC, fedys commented
@rohitp19 you can start your code review now.

2024-07-10 05:56 UTC, rohitp19 commented
@rahuld-dev It looks like it is not deployed to beta correctly. Can you please check?

2024-07-10 12:43 UTC, rohitp19 submitted a review, later dismissed
Thanks @rahuld-dev Tested on https://rohitaws1.qa.acs.acquia.io/.

2024-07-11 08:20 UTC, fedys approved these changes
Thanks @rahuld-dev!

2024-07-11 08:21 UTC, fedys commented
@rohitp19 you can start your code review.

2024-07-11 10:27 UTC, avikarshasaha approved these changes
Tested in beta! Thanks @rahuld-dev

2024-07-11 12:28 UTC, merged